version: '3'
services:

  elk:
    image: sebp/elk
    container_name: elk
    ports:
      - 5601:5601
    volumes:
      - ./elastic/logstash/pipeline.conf:/etc/logstash/conf.d/pipeline.conf:ro

  filebeat:
    image: elastic/filebeat:7.9.3
    container_name: filebeat
    restart: on-failure
    user: root
    volumes:
      - ./elastic/filebeat/docker.filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - elk

  mongo:
    image: mongo
    container_name: idv-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: welcome
      MONGO_INITDB_DATABASE: idv-local
    ports:
      - 27018:27017
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  aws-services:
    image: localstack/localstack:latest
    container_name: aws-services
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d
    environment:
      - AWS_ACCESS_KEY_ID=abc
      - AWS_SECRET_ACCESS_KEY=123
      - DEFAULT_REGION=eu-west-1
      - SERVICES=sns,ses

  idv-context-spring-app:
    image: michaelruocco/idv-context-spring-app:${CONTEXT_APP_VERSION}
    container_name: idv-context-spring-app
    mem_limit: 2048m
    mem_reservation: 2048m
    ports:
      - 8081:80
    environment:
      - SERVER_PORT=80
      - SPRING_PROFILES_ACTIVE=simple-logging
      - MONGO_CONNECTION_STRING=mongodb://idv:welcome01@idv-mongo:27017/idv-local
      - EXTERNAL_DATA_TIMEOUT=1000
      - EXTERNAL_PHONE_NUMBER_DELAY=750
      - EXTERNAL_EMAIL_ADDRESS_DELAY=500
      - REQUEST_LOGGING_ENABLED=true
      - RESPONSE_LOGGING_ENABLED=true
    depends_on:
      - mongo
      #- filebeat

  idv-one-time-passcode-app:
    image: michaelruocco/idv-one-time-passcode-spring-app:${OTP_APP_VERSION}
    container_name: idv-one-time-passcode-app
    mem_limit: 2048m
    mem_reservation: 2048m
    ports:
      - 8082:80
    environment:
      - SERVER_PORT=80
      - SPRING_PROFILES_ACTIVE=simple-logging
      - CONTEXT_URI=http://host.docker.internal:8081
      - AWS_ACCESS_KEY=abc
      - AWS_SECRET_KEY=123
      - AWS_SNS_ENDPOINT_URI=http://aws-services:4566
      - AWS_SES_ENDPOINT_URI=http://aws-services:4566
      - MONGO_CONNECTION_STRING=mongodb://idv:welcome01@idv-mongo:27017/idv-local
      - REQUEST_LOGGING_ENABLED=true
      - RESPONSE_LOGGING_ENABLED=true
    depends_on:
      - aws-services
      - mongo
      - idv-context-spring-app
      #- filebeat